name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # ou la version que tu utilises

    # Installer les dépendances
    - name: Install dependencies
      run: |
        cd backend
        npm install

    # Lancer les tests
    - name: Run tests
      run: |
        cd backend
        npm test

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest .

    # Push Docker image
    - name: Push Docker image to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest

