name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Installation des dépendances
    - name: Install dependencies
      run: |
        cd backend
        npm install

    # 4. Lancement des tests
    - name: Run tests
      run: |
        cd backend
        npm test

    # 5. Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest .

    # 6. Push vers Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-app:latest
